image: python2.7
env:
  - OWL_ENV="local"
script:
  - cd courseowl_django
  - psql -c "create database owl;" -U postgres -h 127.0.0.1
  - psql -c "create user owl with password 'qwerty123';" -U postgres -h 127.0.0.1
  - psql -c "alter user owl CREATEDB;" -U postgres -h 127.0.0.1
  - psql -c "grant all privileges on database owl to owl;" -U postgres -h 127.0.0.1
  - pip install -r requirements.txt --use-mirrors
  - ./manage.py test
services:
  - postgres:9.1
notify:
  email:
    recipients:
      - crimsonredmk@gmail.com
      - zkang3@illinois.edu
      - aksuniv@gmail.com
    on_success: false
    on_failure: true
